version: '3.8'

services:
  db:
    image: postgres:16
    container_name: url-shortener-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortener
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: node:20
    container_name: nest_app
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npx prisma generate && npx prisma migrate dev --name init && yarn install && yarn start:dev"

volumes:
  pgdata:
